ruby haikufinder-wpapi.rb 'https://observer.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.mountainvalleynews.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://pmnewsnigeria.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thedmonline.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dailysignal.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.businesstimes.co.tz//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.themonitor.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.xeniagazette.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://news.harvard.edu/gazette//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.banglamirrornews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.yadkinripple.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thegeorgeanne.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://ptreyeslight.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.ocracokeobserver.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.valleymorningstar.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.commonwealthtimes.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://theonefeather.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.weeklyblitz.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.leaderherald.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thestandardnewspaper.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.therugbypaper.co.uk//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://missionlocal.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.nationalreport.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.uticaphoenix.net/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dmcityview.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.norj.ca/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.in-cyprus.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.summitdaily.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.ardmoreite.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.tidewaternews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.archpaper.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.mercurynews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.pakobserver.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://fwweekly.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://indianapolisrecorder.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.pbn.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dailysquib.co.uk//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://northernstandard.ie/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.paradisepost.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thetriangle.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.elkintribune.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.alive.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.bangordailynews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.lionsroar.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.times-age.co.nz/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.redbluffdailynews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.outinperth.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.centerforpolitics.org/crystalball/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.pressandjournal.co.uk/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.hillsdalecollegian.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.crookstontimes.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://edn.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.fortsaskatchewanrecord.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thecivilian.co.nz//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://theprovince.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.easyreadernews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.mediafiledc.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thenonleaguefootballpaper.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.deltadiscovery.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://wkuherald.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://egyptindependent.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.cochranetimespost.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.krakowpost.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.journalpress.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.southwarknews.co.uk//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.bancroftthisweek.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://sfpublicpress.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://americanfreepress.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.cornwallseawaynews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.championnews.com.ng//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.theneweuropean.co.uk/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.oaklandpostonline.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://guardianlv.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://guyanatimesgy.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.westernweekender.com.au//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.munster-express.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.sonomanews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://nagalandpost.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.hawaii247.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.abbynews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.jpinews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://eugenedailynews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.russellcountynewspapers.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.claxtonenterprise.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.eldoradotimes.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thekansan.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.goldcoast.com.au/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.chaser.com.au/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://gaysifamily.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.steamboatpilot.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.wnewsj.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.tell.ng//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.garnett-ks.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.koorimail.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.losbanosenterprise.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.ourvalleyvoice.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.westmeathexaminer.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.atokacountytimes.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.indiawest.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.goondiwindiargus.com.au/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.newsjournal.com.ng//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.goldcoastbulletin.com.au//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thehilltoponline.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://thecurrent-online.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.leoweekly.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.lajuntatribunedemocrat.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.spec.com.au//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://boholchronicle.com.ph/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.twincities.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://savejersey.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://thekashmirimages.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://pressherald.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://arktimes.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.cccadvocate.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://themiamipost.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thinkersnewsng.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://dailytimesng.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.mindentimes.ca//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.anglocelt.ie/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.cats.com.sg/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.mountolivetribune.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thesundaymail.com.au/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.humortimes.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.concrete-herald.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://philadelphiaweekly.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.highlandstoday.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://thevermontstandard.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dng24.co.uk//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.ysnews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://thewestfieldnews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.jewishpress.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.clintonnewsrecord.ca/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.sydneyobserver.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.houstonianonline.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thedaily.sk//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dailyorange.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://universe.byu.edu/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.draytonvalleywesternreview.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.parkrecord.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.monett-times.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://nique.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://themeghalayan.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.paisano-online.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://syracusenewtimes.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.ripplesnigeria.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://miamicelebrities.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.gilroydispatch.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://tmtimes.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.hippopress.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://sfbayview.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.redpepper.co.ug/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.topic.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://cuindependent.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.couriermail.com.au/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.losangelesblade.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.pinchercreekecho.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.tribune.net.ph/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://williamsrecord.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thetelegraph.com.au/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.searchlight.vc//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://oxfordleader.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dailytrojan.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://nyunews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.tuamherald.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.akronnewsreporter.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.blackchronicle.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.leaderunion.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://dailysport.co.uk/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.orissapost.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://5tjt.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://thegoodlifesurbiton.co.uk//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://badgerherald.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.hometownjournal.biz/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.smdp.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.evnreport.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.fortmacleodgazette.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://edmontonjournal.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.theweekender.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.aspentimes.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.pressdemocrat.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.cw.ua.edu//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.phuketgazette.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.therakyatpost.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.oneidadispatch.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://peresdaily.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.sbstatesman.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.thenews.coop//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://thechenabtimes.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://miamisunpost.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.elizabethton.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.chicagoreader.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://thetablet.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://voxeurop.eu/en//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://haitiantimes.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.defense-update.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.gctelegram.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.ntnews.com.au//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.bullandbearmcgill.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.riotimesonline.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.sbsun.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.eastbaytimes.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://premiumtimesng.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.SBRChina.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thestarnews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://theshillongtimes.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://keizertimes.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.washingtoninformer.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://bowdoinorient.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://theava.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.pratttribune.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://chicagocrusader.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://thegraftonnews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.larchmontchronicle.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://riverviewobserver.net/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://tntribune.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.devilslakejournal.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.khmertimeskh.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://mrfixitstips.co.uk//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.midnorthmonitor.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.postnewsgroup.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://utahstories.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.longislandexchange.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://northernstar.info/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.mtairynews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://boulderweekly.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.maturetimes.co.uk/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://scdailypress.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://pelhamexaminer.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.niagarafallsreporter.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.sidneydailynews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://kashmirobserver.net/index.php/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://dailytrust.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.theislanderonline.com.au//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.record-bee.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://washingtonblade.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.anarchymag.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://mailtribune.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.napaneeguide.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.colacherald.com.au///wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.themichigantimes.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.businessbhutan.bt/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.compassnewspaper.com.ng//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.timesgazette.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://amsterdamnews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dailytidings.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.Pajhwok.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.thescottishsun.co.uk//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://artvoice.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dunoon-observer.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.villagevoice.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://telanganatoday.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.dailydemocrat.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.ghanaiantimes.com.gh/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.bvibeacon.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.us-inquirer.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.kingstonthisweek.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.todaysfarmer.ca/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://daily-iowan.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.tripolipost.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://dailypost.ng//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.examiner.net/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.thehudsonindependent.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://fortworthbusiness.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.wellingtonadvertiser.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://brandeishoot.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://jonews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://ncreview.com.au/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.sunnewsonline.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.nenaghguardian.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.daltonkidronnews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://thehill.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thesubtimes.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thecourier.co.uk/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.afro.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.namibian.com.na//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://mountaintimes.info//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.streetsheet.org/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://limaohio.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.washcountynews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.BroadsideOnline.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.haliburtonecho.ca/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.chathamthisweek.ca/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.trentonian.ca//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://clarechampion.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.urbanacitizen.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://blackvoicenews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.kincardinenews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.collegian.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://chicagomaroon.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://muslimnews.com.ng//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.bmamag.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.lanthorn.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.current.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://crestedbuttenews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://coyotechronicle.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thereporteronline.net/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://atascaderonews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.corpcommsmagazine.co.uk//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.spotlightnews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.washingtonjewishweek.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://nationalpost.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.michigandaily.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.fiusm.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.unfspinnaker.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.theridernews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://dailycampus.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.jacksoncountypilot.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.portpirierecorder.com.au/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.sentinelcolorado.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://thecoaster.net/wordpress//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://thedailyguardian.net/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.delgazette.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.rabwah.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.coinagemag.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://bocabeacon.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dallasvoice.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.sgvtribune.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://islandtimes.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.hillsborofreepress.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.statetimes.in//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.eastbayexpress.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://vancouversun.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thelantern.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://kykernel.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thecaliforniacourier.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://dominionpost.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.lakeshoreadvance.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.oaoa.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.manitoulin.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://canyon-news.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.jweekly.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://londonderrytimes.net/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.pe.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.whitecourtstar.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.register-pajaronian.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.spacing.ca/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.taylordailypress.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://laotiantimes.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.thepitchkc.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.rep-am.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.italianamericanherald.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.laurinburgexchange.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://merciad.mercyhurst.edu//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://thenigeriastandard.ng/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.chillicothenews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.ottawaherald.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.jewishtimes.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://thehardtimes.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.churchnewspaper.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.weeklypostnc.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.andalusiastarnews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.hdnews.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://coloradosun.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.theindiareview.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.flathatnews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.bcheights.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.cardinalcourieronline.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://thegavoice.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.heralddemocrat.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.portsmouth-dailytimes.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dailyjournal.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.dailycal.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.gazettechicago.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://fountainhopper.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://thefrontierpost.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.mainlinemedianews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.hollywoodreporter.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://ansonrecord.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.leavenworthtimes.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.gwhatchet.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.psuvanguard.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.villagemagazine.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.augustagazette.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.catholictranscript.org/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://southsideweekly.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.punchng.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://thecarrollnews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.tulanehullabaloo.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.marcellusnews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://modernfix.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.carlow-nationalist.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.theoregonjournal.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.myvillager.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.asianfortunenews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.huntnewsnu.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://tnhdigital.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://hallmarknews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.iowastatedaily.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://catholicherald.co.uk//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.pittnews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.lasentinel.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.news-bulletin.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.muscatdaily.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.showbusinessweekly.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://euromaidanpress.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://mg.co.za//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.pittsburghcatholic.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.theaquarian.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://theaggie.org///wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.limerickpost.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.thekansan.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.cambodiadaily.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.themiamihurricane.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://leominsterchamp.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.boonvilledailynews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://vaildaily.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://gazette.ireland.anglican.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thetidenewsonline.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://myspringfieldpaper.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://brownwoodtx.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://mainecampus.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.ncnewspress.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.georgiatoday.ge//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.kstatecollegian.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://geelongindy.com.au//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.fijitimes.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.taylorsvilletimes.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.con-telegraph.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dailyillini.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.ctmirror.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://sonorannews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://nhgazette.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.easternherald.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://baptistmessenger.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.sdjewishjournal.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.sparechangenews.net/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://dailypost.in/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.njtoday.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.butlercountytimesgazette.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://betterdwelling.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.oamarumail.co.nz/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.cassville-democrat.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.mcphersonsentinel.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.nineoclock.ro//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.inishowenindo.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.voiceofsandiego.org/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://TheLewisFlyer.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.wellingtondailynews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dailynorthwestern.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thechronicle.com.au/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.morganhilltimes.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.petaluma360.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://soledadbee.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.asianjournal.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dailybruin.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.fairborndailyherald.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://elamerican.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://greystar.co.nz//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.georgiastatesignal.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dailyadvocate.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.smmirror.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.catalystmagazine.net/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.capitalethiopia.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.ksusentinel.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.news-star.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://folioweekly.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.civilbeat.org/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.thekashmirmonitor.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.bladenjournal.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.ftleavenworthlamp.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://waterford-news.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://therconline.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://chinaeconomicreview.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://corkindependent.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.dailyexcelsior.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.jerseyeveningpost.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://mauinow.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.concordiensis.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.katoikos.eu//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.lawrencecountypress.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://aquinas.scranton.edu//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.ucsdguardian.org/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://corporatedispatch.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.indyweek.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.qctonline.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://postnewsgroup.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://nigerianobservernews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.eptrail.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.gtweekly.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.austindailyherald.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.solomonstarnews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.busiweek.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.westernpeople.ie//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.bcdemocrat.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.postindependent.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thenewjournalandguide.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.jewishexponent.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.travelextra.ie/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.jamestownpress.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.atinitonews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.dailybulletin.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.thevoicebw.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.malibutimes.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.marshallnews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.nevadasagebrush.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.northernnews.ca/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://frontpageafricaonline.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://horizonweekly.ca//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.recordherald.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.the74million.org/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.geelongadvertiser.com.au//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.vsuspectator.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.theborneopost.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://breaking9to5.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.bcrnews.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.lakemchenryscanner.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.triblive.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.whittierdailynews.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://rockrivertimes.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.goaprism.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.multihousingnews.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://millburysutton.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://www.saratogian.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://tucollegian.org/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.pacificcitizen.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.citypaper.net//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://thenewyorkage.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.mvtimes.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.michiganreview.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.brownpoliticalreview.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'https://leveller.live//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.richfieldreaper.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://wesleying.org//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dominicantoday.com/wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
ruby haikufinder-wpapi.rb 'http://www.dodgeglobe.com//wp-json/wp/v2/posts?search=&per_page=100&orderby=date&order=desc' >> found_haikus.txt
